[package]
name = "talos-name-service"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
ttl-manager = { path = "../ttl_manager" }
pause-control = { path = "../pause_control" }

[dev-dependencies]
talos-registry = { path = "../talos_registry" }
proptest = "1.4"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }

