-- ─── Backup Runs (DR audit trail) ────────────────────────────────
--
-- One row per backup or restore attempt. Additive, non-destructive
-- (no FK references that could prevent restores of incompatible prior states).
--
-- IDs are CUID2 strings generated by the application. status is one of:
--   'pending' | 'running' | 'completed' | 'failed' | 'cancelled'
-- op is 'backup' | 'restore' | 'verify'.
-- scope is 'system' (full Postgres + agent state coverage) | 'config' (env/metadata only).

CREATE TABLE "tls_backup_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"op" text NOT NULL,
	"scope" text NOT NULL,
	"talosId" text,
	"agentId" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"triggeredBy" text,
	"artifactPath" text,
	"encryption" text,
	"sizeBytes" bigint,
	"sha256" text,
	"durationMs" integer,
	"errorMessage" text,
	"metadata" jsonb,
	"startedAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"finishedAt" timestamp(3)
);
--> statement-breakpoint

CREATE INDEX "tls_backup_runs_status_idx" ON "tls_backup_runs" USING btree ("status" text_ops);
--> statement-breakpoint
CREATE INDEX "tls_backup_runs_startedAt_idx" ON "tls_backup_runs" USING btree ("startedAt" text_ops);
--> statement-breakpoint
CREATE INDEX "tls_backup_runs_op_status_idx" ON "tls_backup_runs" USING btree ("op" text_ops,"status" text_ops);
--> statement-breakpoint

ALTER TABLE "tls_backup_runs" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "auth_all_backup_runs" ON "tls_backup_runs" FOR ALL TO authenticated USING (true) WITH CHECK (true);
--> statement-breakpoint
CREATE POLICY "postgres_all_backup_runs" ON "tls_backup_runs" FOR ALL TO postgres USING (true) WITH CHECK (true);
