#!/usr/bin/env node
/**
 * check-openapi-sdk-drift.test.mjs
 *
 * Unit tests for scripts/check-openapi-sdk-drift.mjs.
 *
 * Covers positive, negative, boundary, and regression cases for:
 *   - OpenAPI snapshot structural validation
 *   - SDK types drift heuristic checks
 *   - Privacy guard
 *   - CLI argument parsing
 *
 * Run locally:
 *   node --test scripts/check-openapi-sdk-drift.test.mjs
 *
 * Exit codes follow node:test conventions (0 = all pass, non-zero = failures).
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCRIPT = resolve(__dirname, "check-openapi-sdk-drift.mjs");

// ── Fixtures ──────────────────────────────────────────────────────────────────

const VALID_SNAPSHOT = JSON.stringify(
  {
    openapi: "3.1.0",
    info: { title: "Talos Protocol API", version: "0.1.0" },
    paths: {
      "/api/talos": {
        get: {
          operationId: "listTalos",
          responses: { "200": { description: "OK" } },
        },
        post: {
          operationId: "createTalos",
          responses: { "201": { description: "Created" } },
        },
      },
      "/api/talos/{id}": {
        get: {
          operationId: "getTalos",
          responses: { "200": { description: "OK" } },
        },
      },
    },
    components: { schemas: {} },
  },
  null,
  2,
) + "\n";

// Minimal generated-types.ts that contains all snapshot paths
const VALID_TYPES = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/api/talos": {
    get: {
      responses: { 200: { content: { "application/json": unknown } } };
    };
    post: {
      responses: { 201: { content: { "application/json": unknown } } };
    };
  };
  "/api/talos/{id}": {
    get: {
      responses: { 200: { content: { "application/json": unknown } } };
    };
  };
};

export type components = { schemas: Record<string, never> };
export type operations = Record<string, never>;
`;

// ── Helpers ───────────────────────────────────────────────────────────────────

let _tmpDir = null;

function getTmpDir() {
  if (!_tmpDir) {
    _tmpDir = join(tmpdir(), `drift-test-${process.pid}`);
    mkdirSync(_tmpDir, { recursive: true });
  }
  return _tmpDir;
}

function tmpFile(name, content) {
  const fp = join(getTmpDir(), name);
  writeFileSync(fp, content, "utf8");
  return fp;
}

function runDrift(...args) {
  const result = spawnSync(
    process.execPath,
    [SCRIPT, ...args],
    { encoding: "utf8", timeout: 30_000 },
  );
  return {
    status: result.status,
    stdout: result.stdout || "",
    stderr: result.stderr || "",
  };
}

process.on("exit", () => {
  if (_tmpDir && existsSync(_tmpDir)) {
    try { rmSync(_tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
  }
});

// ── Snapshot – positive ───────────────────────────────────────────────────────

describe("OpenAPI snapshot – positive", () => {
  it("accepts a valid snapshot with --skip-types", () => {
    const sp = tmpFile("valid.snapshot.json", VALID_SNAPSHOT);
    const { status, stdout } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 0, `Expected 0, got ${status}\nstdout: ${stdout}`);
    assert.match(stdout, /✓/);
  });

  it("reports JSON output with --json --skip-types", () => {
    const sp = tmpFile("valid-json.snapshot.json", VALID_SNAPSHOT);
    const { status, stdout } = runDrift("--snapshot", sp, "--skip-types", "--json");
    assert.strictEqual(status, 0);
    const parsed = JSON.parse(stdout);
    assert.strictEqual(parsed.failed, 0);
    assert.ok(parsed.checks.every((c) => c.ok));
  });

  it("accepts OpenAPI 3.0.x version string", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.openapi = "3.0.3";
    const sp = tmpFile("oas-3.0.sn.json", JSON.stringify(doc, null, 2));
    const { status } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 0);
  });

  it("accepts snapshot with many paths", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    for (let i = 0; i < 20; i++) {
      doc.paths[`/api/resource-${i}`] = {
        get: { responses: { "200": { description: "OK" } } },
      };
    }
    const sp = tmpFile("many-paths.sn.json", JSON.stringify(doc, null, 2));
    const { status } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 0);
  });
});

// ── Snapshot – negative ───────────────────────────────────────────────────────

describe("OpenAPI snapshot – negative / error cases", () => {
  it("rejects a missing snapshot file", () => {
    const { status, stderr } = runDrift(
      "--snapshot",
      "/tmp/does-not-exist-openapi-drift-test.json",
      "--skip-types",
    );
    assert.strictEqual(status, 1);
    assert.match(stderr, /not found|cd web/i);
  });

  it("rejects an empty snapshot file", () => {
    const sp = tmpFile("empty.sn.json", "");
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /empty/i);
  });

  it("rejects invalid JSON in snapshot", () => {
    const sp = tmpFile("bad-json.sn.json", "{ openapi: 3 not json }");
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /not valid JSON/i);
  });

  it("rejects missing openapi version field", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    delete doc.openapi;
    const sp = tmpFile("no-openapi.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /openapi/i);
  });

  it("rejects non-3.x openapi version (e.g. 2.0)", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.openapi = "2.0.0";
    const sp = tmpFile("oas2.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /3\.x\.y/i);
  });

  it("rejects missing info object", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    delete doc.info;
    const sp = tmpFile("no-info.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /info/i);
  });

  it("rejects missing info.title", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    delete doc.info.title;
    const sp = tmpFile("no-title.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /title/i);
  });

  it("rejects missing info.version", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    delete doc.info.version;
    const sp = tmpFile("no-ver.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /version/i);
  });

  it("rejects missing paths object", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    delete doc.paths;
    const sp = tmpFile("no-paths.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /paths/i);
  });

  it("rejects empty paths object", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.paths = {};
    const sp = tmpFile("empty-paths.sn.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /empty paths/i);
  });
});

// ── Snapshot – boundary ───────────────────────────────────────────────────────

describe("OpenAPI snapshot – boundary", () => {
  it("accepts snapshot with exactly one path", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.paths = {
      "/api/health": {
        get: { responses: { "200": { description: "OK" } } },
      },
    };
    const sp = tmpFile("one-path.sn.json", JSON.stringify(doc, null, 2));
    const { status } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 0);
  });

  it("produces a warning (not error) for path with no HTTP methods", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.paths["/api/no-methods"] = { "x-extension": "custom" };
    const sp = tmpFile("ext-path.sn.json", JSON.stringify(doc, null, 2));
    const { status, stdout } = runDrift("--snapshot", sp, "--skip-types");
    // Should pass (warnings don't fail)
    assert.strictEqual(status, 0);
    assert.match(stdout + "", /warning|✓/i);
  });
});

// ── SDK types drift heuristic ─────────────────────────────────────────────────

describe("SDK types drift – heuristic checks", () => {
  it("passes when types file contains all snapshot paths", () => {
    const sp = tmpFile("types-ok.sn.json", VALID_SNAPSHOT);
    const tp = tmpFile("valid-types.ts", VALID_TYPES);
    const { status, stdout } = runDrift("--snapshot", sp, "--types", tp);
    assert.strictEqual(status, 0, `stdout: ${stdout}`);
  });

  it("rejects a missing types file", () => {
    const sp = tmpFile("types-missing.sn.json", VALID_SNAPSHOT);
    const { status, stderr } = runDrift(
      "--snapshot",
      sp,
      "--types",
      "/tmp/does-not-exist-generated-types.ts",
    );
    assert.strictEqual(status, 1);
    assert.match(stderr, /not found|generate:types/i);
  });

  it("rejects an empty types file", () => {
    const sp = tmpFile("types-empty.sn.json", VALID_SNAPSHOT);
    const tp = tmpFile("empty.ts", "");
    const { status, stderr } = runDrift("--snapshot", sp, "--types", tp);
    assert.strictEqual(status, 1);
    assert.match(stderr, /empty/i);
  });

  it("rejects a types file with no export type / export interface", () => {
    const sp = tmpFile("types-noexport.sn.json", VALID_SNAPSHOT);
    const tp = tmpFile("no-exports.ts", "const foo = 'bar';\n");
    const { status, stderr } = runDrift("--snapshot", sp, "--types", tp);
    assert.strictEqual(status, 1);
    assert.match(stderr, /openapi-typescript/i);
  });

  it("rejects types file missing a snapshot path", () => {
    const sp = tmpFile("types-drift.sn.json", VALID_SNAPSHOT);
    // Types file missing "/api/talos/{id}" path
    const incompleteTypes = VALID_TYPES.replace('"/api/talos/{id}"', '"__removed__"');
    const tp = tmpFile("incomplete-types.ts", incompleteTypes);
    const { status, stderr } = runDrift("--snapshot", sp, "--types", tp);
    assert.strictEqual(status, 1);
    assert.match(stderr, /missing.*path|generate:types/i);
  });

  it("--skip-types skips the types drift check", () => {
    const sp = tmpFile("skip-types.sn.json", VALID_SNAPSHOT);
    // Even with an invalid types path, --skip-types should pass
    const { status } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 0);
  });

  it("types drift check reports all missing paths (up to cap)", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    // Add 10 paths not in the types file
    for (let i = 0; i < 10; i++) {
      doc.paths[`/api/missing-path-${i}`] = {
        get: { responses: { "200": { description: "OK" } } },
      };
    }
    const sp = tmpFile("many-missing.sn.json", JSON.stringify(doc, null, 2));
    const tp = tmpFile("old-types.ts", VALID_TYPES); // no new paths
    const { status, stderr } = runDrift("--snapshot", sp, "--types", tp);
    assert.strictEqual(status, 1);
    // Should mention "and N more" cap
    assert.match(stderr, /more|generate:types/i);
  });
});

// ── Privacy guard ─────────────────────────────────────────────────────────────

describe("Privacy guard", () => {
  it("rejects a snapshot containing a PEM private key header", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.info["x-internal"] = "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAA==";
    const sp = tmpFile("pem-snap.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /sensitive-data pattern/i);
    // The key value must NOT appear in the error output
    assert.ok(!stderr.includes("MIIEowIBAA"), "PEM value must not be echoed");
  });

  it("rejects a snapshot containing a secret assignment", () => {
    const doc = JSON.parse(VALID_SNAPSHOT);
    doc.info["x-service-key"] = "api_key: supersecret_value_1234567890abcdef";
    const sp = tmpFile("secret-snap.json", JSON.stringify(doc, null, 2));
    const { status, stderr } = runDrift("--snapshot", sp, "--skip-types");
    assert.strictEqual(status, 1);
    assert.match(stderr, /sensitive-data pattern/i);
    assert.ok(!stderr.includes("supersecret_value"), "secret must not be echoed");
  });
});

// ── CLI argument parsing ──────────────────────────────────────────────────────

describe("CLI usage errors", () => {
  it("exits 2 with unknown argument", () => {
    const { status } = runDrift("--unknown-flag");
    assert.strictEqual(status, 2);
  });

  it("exits 2 when --snapshot has no path", () => {
    const { status } = runDrift("--snapshot");
    assert.strictEqual(status, 2);
  });

  it("exits 2 when --types has no path", () => {
    const { status } = runDrift("--types");
    assert.strictEqual(status, 2);
  });
});

// ── Regression: real snapshot structure ──────────────────────────────────────

describe("Regression – real repo snapshot", () => {
  it("real openapi.snapshot.json passes structural checks", () => {
    // Uses the actual committed snapshot (not a tmp file)
    const { status, stdout, stderr } = runDrift("--skip-types");
    // The real snapshot should always be valid structurally
    assert.strictEqual(
      status,
      0,
      `Real snapshot failed structural check!\nstdout: ${stdout}\nstderr: ${stderr}`,
    );
  });

  it("real generated-types.ts contains real snapshot paths", () => {
    // Uses actual committed files — validates they are in sync
    const { status, stdout, stderr } = runDrift();
    assert.strictEqual(
      status,
      0,
      `Drift detected between committed snapshot and generated-types!\n` +
        `stdout: ${stdout}\nstderr: ${stderr}\n` +
        `Fix: cd packages/sdk && pnpm generate:types && commit`,
    );
  });
});
